version: 0.1

phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - echo Nothing to do yet
artifiacts:
  files:
   -index.html
   -favicon.ico
   -JJamesResume.docx
   -server.js
   -styles/*
   -images/*
