version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - npm install
      - npm run webpack
artifacts:  
  files:
    - index.html
    - favicon.ico
    - JJamesResume.docx
    - style.css
    - styles/*
    - images/*
    - dist/bundle.js
    - media/*
    - src/*